"""empty message

Revision ID: 1932e0baeef5
Revises: 2cf611c723cf
Create Date: 2021-06-08 11:19:03.129641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1932e0baeef5'
down_revision = '2cf611c723cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=True))

    # ### end Alembic commands ###
