"""empty message

Revision ID: 47e1c95a9732
Revises: 617c94451d4d
Create Date: 2021-06-08 14:23:51.278334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e1c95a9732'
down_revision = '617c94451d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
