"""empty message

Revision ID: e502d10b6f5e
Revises: 47e1c95a9732
Create Date: 2021-06-08 14:24:35.181882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e502d10b6f5e'
down_revision = '47e1c95a9732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
